const HamburgerMenuList = [
  {
    id: 1,
    itemName: "Trending",
    isTitle: true,
    isMenu: false,
    menu: [],
  },
  {
    id: 2,
    itemName: "Best Sellers",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 3,
    itemName: "New Releases",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 4,
    itemName: "Movers and Shakers",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 5,
    itemName: "Digital Content And Devices",
    isTitle: true,
    isMenu: false,
    menu: [],
  },
  {
    id: 6,
    itemName: "Echo & Alexa",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 7,
    itemName: "Fire TV",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 8,
    itemName: "Kindle E-Readers & eBooks",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 9,
    itemName: "Audible Audiobooks",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 10,
    itemName: "Amazon Prime Video",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 11,
    itemName: "Amazon Prime Music",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 12,
    itemName: "Shop By Department",
    isTitle: true,
    isMenu: false,
    menu: [],
  },
  {
    id: 13,
    itemName: "Mobiles, Computers",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 14,
    itemName: "TV, Appliances, Electronics",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 15,
    itemName: "Men's Fashion",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 16,
    itemName: "Women's Fashion",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 17,
    itemName: "Home, Kitchen, Pets",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 18,
    itemName: "Beauty, Health, Grocery",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 19,
    itemName: "Sports, Fitness, Bags, Luggage",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 20,
    itemName: "Toys, Baby Products, Kids' Fashion",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 21,
    itemName: "Car, Motorbike, Industrial",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 22,
    itemName: "Books",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 23,
    itemName: "Movies, Music & Video Games",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 25,
    itemName: "Programs & Features",
    isTitle: true,
    isMenu: false,
    menu: [],
  },
  {
    id: 26,
    itemName: "Gift Cards & Mobile Recharges",
    isTitle: false,
    isMenu: true,
    menu: [],
  },
  {
    id: 27,
    itemName: "Flight Tickets",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 28,
    itemName: "#FoundItOnAmazon",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 29,
    itemName: "Clearance store",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 30,
    itemName: "Help & Settings",
    isTitle: true,
    isMenu: false,
    menu: [],
  },
  {
    id: 31,
    itemName: "Your Account",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 32,
    itemName: "Customer Service",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
  {
    id: 33,
    itemName: "Sign In",
    isTitle: false,
    isMenu: false,
    menu: [],
  },
];

export default HamburgerMenuList;
